export const directoryFixtures = [
  {
    id: "valid-root-static",
    source: "projects/valid-root-static",
    classification: "accepted",
    stage: "analysis",
    expectedCode: null,
    summary: "A static site with index.html at the archive root is accepted unchanged.",
  },
  {
    id: "valid-wrapper-static",
    source: "projects/valid-wrapper-static",
    classification: "repairable",
    stage: "normalization",
    expectedCode: "MOVE_WRAPPER",
    summary: "One unambiguous wrapper directory is moved to the canonical root.",
  },
  {
    id: "missing-index",
    source: "projects/missing-index",
    classification: "rejected",
    stage: "analysis",
    expectedCode: "ENTRYPOINT_MISSING",
    summary: "A project without index.html is rejected.",
  },
  {
    id: "missing-referenced-image",
    source: "projects/missing-referenced-image",
    classification: "repairable",
    stage: "normalization",
    expectedCode: "MISSING_LOCAL_REFERENCE",
    summary: "A missing local image is reported and must be repaired before deployment.",
  },
  {
    id: "incorrect-filename-capitalization",
    source: "projects/incorrect-filename-capitalization",
    classification: "repairable",
    stage: "normalization",
    expectedCode: "FIX_REFERENCE_CAPITALIZATION",
    summary: "A uniquely resolvable filename-capitalization mismatch is repaired deterministically.",
  },
  {
    id: "absolute-local-filesystem-path",
    source: "projects/absolute-local-filesystem-path",
    classification: "repairable",
    stage: "normalization",
    expectedCode: "LOCAL_ABSOLUTE_PATH",
    summary: "A file:// reference to a developer machine is reported and cannot be deployed unchanged.",
  },
  {
    id: "localhost-reference",
    source: "projects/localhost-reference",
    classification: "repairable",
    stage: "normalization",
    expectedCode: "LOCALHOST_REFERENCE",
    summary: "A localhost URL is reported and cannot be deployed unchanged.",
  },
  {
    id: "disallowed-executable-extension",
    source: "projects/disallowed-executable-extension",
    classification: "rejected",
    stage: "validation",
    expectedCode: "FILE_TYPE_NOT_ALLOWED",
    summary: "A shell script is rejected by the static-project file allowlist.",
  },
  {
    id: "ambiguous-multiple-sites",
    source: "projects/ambiguous-multiple-sites",
    classification: "rejected",
    stage: "analysis",
    expectedCode: "PROJECT_UNSUPPORTED",
    summary: "Two wrapper directories containing index.html are rejected rather than guessed.",
  },
];

export const generatedDirectoryFixtures = [
  {
    id: "unexpected-binary-text-content",
    generatedPath: "projects/unexpected-binary-text-content",
    classification: "rejected",
    stage: "validation",
    expectedCode: "FILE_TYPE_NOT_ALLOWED",
    summary: "A .txt file containing null and non-text bytes is rejected by content validation.",
  },
];

export const generatedArchiveFixtures = [
  {
    id: "excessive-directory-depth",
    archiveName: "excessive-directory-depth.zip",
    classification: "rejected",
    stage: "archive",
    expectedCode: "ARCHIVE_LIMIT_EXCEEDED",
    summary: "An entry deeper than twelve directories is rejected.",
  },
  {
    id: "path-traversal-archive",
    archiveName: "path-traversal.zip",
    classification: "rejected",
    stage: "archive",
    expectedCode: "ARCHIVE_UNSAFE_PATH",
    summary: "An entry containing a parent traversal segment is rejected.",
  },
  {
    id: "absolute-path-archive",
    archiveName: "absolute-path.zip",
    classification: "rejected",
    stage: "archive",
    expectedCode: "ARCHIVE_UNSAFE_PATH",
    summary: "An archive entry beginning with a filesystem root is rejected.",
  },
  {
    id: "symlink-archive",
    archiveName: "symlink.zip",
    classification: "rejected",
    stage: "archive",
    expectedCode: "ARCHIVE_UNSAFE_PATH",
    summary: "An entry marked as a Unix symbolic link is rejected.",
  },
  {
    id: "nested-zip-archive",
    archiveName: "nested-zip.zip",
    classification: "rejected",
    stage: "archive",
    expectedCode: "FILE_TYPE_NOT_ALLOWED",
    summary: "A ZIP stored inside another ZIP is rejected by the static MVP policy.",
  },
  {
    id: "file-count-limit",
    archiveName: "file-count-limit.zip",
    classification: "rejected",
    stage: "archive",
    expectedCode: "ARCHIVE_LIMIT_EXCEEDED",
    summary: "An archive containing 501 files exceeds the 500-file limit.",
  },
  {
    id: "single-file-size-limit",
    archiveName: "single-file-size-limit.zip",
    classification: "rejected",
    stage: "archive",
    expectedCode: "ARCHIVE_LIMIT_EXCEEDED",
    summary: "One expanded file larger than 10 MiB is rejected.",
  },
  {
    id: "expanded-size-limit",
    archiveName: "expanded-size-limit.zip",
    classification: "rejected",
    stage: "archive",
    expectedCode: "ARCHIVE_LIMIT_EXCEEDED",
    summary: "Expanded content larger than 50 MiB is rejected even when it compresses well.",
  },
];

export const fixtureCatalog = [
  ...directoryFixtures.map((fixture) => ({ ...fixture, materialization: "committed-directory" })),
  ...generatedDirectoryFixtures.map((fixture) => ({ ...fixture, materialization: "generated-directory" })),
  ...generatedArchiveFixtures.map((fixture) => ({ ...fixture, materialization: "generated-archive" })),
];
